name: my_new_project
version: 1.0.0
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  finance_days:
    materialized: table
    unique_key: date_date
    schema: your_schema_name
    description: Model to calculate finance metrics per day
    sql: finance_days.sql
    config:
      materialized: table
      schedule:
        cron: "0 8 * * *" # Run every day at 08:00 (UTC)
